# Generated by Django 5.1 on 2024-08-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
