# Generated by Django 5.1 on 2024-08-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='text',
            new_name='quote',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='created_at',
        ),
    ]
